name: CMake

on:
  push:
    branches:
      - 'master'
      - 'main'
    # paths:
    # - .github/workflows/cmake.yml
  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.) 
  BUILD_TYPE: retail
  VERSION: RC

jobs:
  linux-build:
    uses: ./.github/workflows/cmake_linux_x64.yml
    with: 
      build_type: retail
      version: RC
